site_name: Graph8 Platform Documentation
nav:
  - Chat UI:
    - Overview: chat-uui/index.md
    - Thread: chat-uui/01_thread.md
    - Message: chat-uui/02_message.md
    - Composer: chat-uui/03_composer.md
    - Content Part: chat-uui/04_content_part.md
    - Runtime: chat-uui/05_runtime.md
    - Assistant Cloud: chat-uui/06_assistant_cloud.md
    - Model Context: chat-uui/07_model_context.md
    - Tools and Tool UI: chat-uui/08_tools_and_tool_ui.md
    - Markdown Text: chat-uui/09_markdown_text.md
    - Assistant Modal: chat-uui/10_assistant_modal.md
docs_dir: output
site_dir: site
theme:
  name: material
  palette:
    primary: 'blue'
    accent: 'light blue'
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - toc
  - admonition
  - codehilite
  - footnotes
  - meta
  - tables
  - pymdownx.superfences
